### PR TITLE
Windows compatibility

### PR DESCRIPTION
**Pull request by ghost**
Related issues:
- https://github.com/yuki-ycino/fzf-preview.vim/issues/182
- https://github.com/yuki-ycino/fzf-preview.vim/issues/177

This PR should fix most of the commands of fzf-preview.vim if installed with coc-nvim, except the ones using
- git_actions_preview
- preview_yankround_register

I ran `yarn test` (on windows only), and every test pass, by I have no easy access to a linux or mac os.
Could you review my code an keep in mind that I am new to vim and that I am not a native English speaker.
Thank you.

### CODE REVIEW

**Comment by yuki-yano** [comment]
Thanks for the PR.

I'm a little busy, so I'll try to do a review in my free time.

The CI was not running against the PR, so I just set it up to run against a pull request.
Can you rebase the master and ask for a push again?

**Comment by yuki-yano** [comment]
It doesn't seem to work when multiple arguments are passed to FromResources.
It may be environment dependent, but can you confirm that it works?

I think this patch should work if the problem is happening.
If you are able to confirm the problem, please incorporate this patch

```diff
diff --git a/src/args/files-from-resources-parser.ts b/src/args/files-from-resources-parser.ts
index 4bb4006..c7fe163 100644
--- a/src/args/files-from-resources-parser.ts
+++ b/src/args/files-from-resources-parser.ts
@@ -1,3 +1,5 @@
+import { flatMap } from "lodash"
+
 import { argsParser } from "@/args/parser"
 import { FILE_RESOURCES } from "@/const/fzf-option"
 import type { SourceFuncArgs } from "@/type"
@@ -6,7 +8,7 @@ export const parseResources = (args: string): SourceFuncArgs => {
   const parser = argsParser()
   const options = parser.parse(args)

-  const resources = options._
+  const resources = flatMap(options._, (resource) => resource.split(","))

   if (resources.length === 0) {
     throw new Error("Select one or more resources")
```

**Comment by yuki-yano** [comment]
I haven't finished reviewing it yet, but is it mandatory to change the `fzfOptionsToString` to `fzfOptionsToStringArray`?
If it's not required, I'd like to incorporate it in another amendment.

**Comment by ghost** [comment]
On my computer, it seem that `FromResources` works with and without your patch on multiple resources.
From the Read me
```vimrc
nnoremap <silent> [fzf-p]p     :<C-u>CocCommand fzf-preview.FromResources project_mru git<CR>
```
I think that your patch should split on space and not comma:
```typescript
const resources = flatMap(options._, (resource) => resource.split(","))
```
should be
```typescript
const resources = flatMap(options._, (resource) => resource.split(" "))
```
The change from `fzfOptionsToString` to `fzfOptionsToStringArray` is not mandatory, but it means that the user must escape correctly some symbols for the `cmd` shell. This escaping is made in `fzf.vim` of the `fzf` plugin:
```vim
function! s:shellesc_cmd(arg)
  let escaped = substitute(a:arg, '[&|<>()@^]', '^&', 'g')
  let escaped = substitute(escaped, '%', '%%', 'g')
  let escaped = substitute(escaped, '"', '\\^&', 'g')
  let escaped = substitute(escaped, '\(\\\+\)\(\\^\)', '\1\1\2', 'g')
  return '^"'.substitute(escaped, '\(\\\+\)$', '\1\1', '').'^"'
endfunction
```
I will update this PR in the week to remove the `fzfOptionsToStringArray` related code.

> I haven't finished reviewing it yet, but is it mandatory to change the `fzfOptionsToString` to `fzfOptionsToStringArray`?
If it's not required, I'd like to incorporate it in another amendment.

Do you want me to do another PR for that ? If so, when do you want me to do it ?

**Comment by yuki-yano** [comment]
When I try it on my friend's environment, it seems that space-separated arguments are converted to a comma-separated list.

This is the behavior on Windows 10 + gVim with coc extensions.
To work around this, I had to use a flatmap to separate them by a comma.

The changes to fzfOptionsToStringArray can be merged before this PR if needed.

**Comment by yuki-yano** [comment]
Execute `:CocCommand fzf-preview.FromResources buffer mru`

`console.log(args)`
Mac: `['buffer', 'mru']`
Windows `['buffer,mru']`

**Comment by yuki-yano** [comment]
We not making much progress, so I'm going to use the PR as a guide to fix this on my end.

**Pull request closed without merging**
