### PR TITLE
Fix devicons performance issues temporary

### PR DESCRIPTION
**Pull request by sheoak**
Refs #128

### CODE REVIEW

**Comment by yuki-yano** [comment]
Sorry for the delay in replying.
I think that's good, can you write down the doc and the README for me?

**Comment by sheoak** [comment]
Yes I can do that!

**Comment by reisnobre** [comment]
That merge would be nice... I'm working on a project that has more than 4k files and I had to disable the devicons

**Comment by sheoak** [comment]
@yuki-ycino i have added the documentation

**Comment by yuki-yano** [comment]
Merged. Thanks

**Comment by yuki-yano** [comment]
Sorry, there was a bug and I'm going to Revert it.

In the `s:discard_prefix_size` function, even if the dev-icons are not needed, it was accidentally It will shorten the file name.

https://github.com/yuki-ycino/fzf-preview.vim/blob/d1d902c267a3f52994941240124467ecf2021029/autoload/fzf_preview/handler.vim#L77-L80

To get around this, you need to set and save a variable when created the resource.
In the current implementation of Vim script, this is a pain.

Instead, I've implemented a TypeScript plugin to do the same thing.
This will be merged into master in the near future.

[`dd9954d` (#133)](https://github.com/yuki-ycino/fzf-preview.vim/pull/133/commits/dd9954d182f4deab38eba367c24016c0e4517190)

**Pull request merged**
